### ISSUE TITLE
Scroll while dragging?

### ISSUE THREAD

**Issue by mahemoff** [pornel/slip#53]
Is it possible to scroll the page while dragging an element?

**Comment by pornel** [comment]
This was implemented in #12. If it's not complete, then it'd be great if you could fix it :)

**Comment by mahemoff** [comment]
Strange, my integration's not working here on OSX Chrome. I'll check later what may be causing it.

**Comment by chriscookz** [comment]
I'm also running into this on Firefox. It works great on Chrome.

**Comment by carter-thaxton** [comment]
I believe this was fixed by #71 and #72.  Feel free to reopen if you find more issues.

**Comment by mahemoff** [comment]
Thanks, it's better now, but I'm still seeing an issue with scrolling to the bottom of the page, where the element can be dragged to the bottom, causing the whole page to stretch vertically.

This is visible in the [live demo](https://kornel.ski/slip/), which points to Slip 1.2, and I've also added it at https://github.com/mahemoff/slip pointing to the latest slip.js with same result.

**Comment by carter-thaxton** [comment]
You're right.  I'll look into it.

**Comment by carter-thaxton** [comment]
@mahemoff Check out the latest commit.  Should fix your issue.  Note that the source now also contains the example code.

@pornel I think you'll still need to update your [live demo](https://kornel.ski/slip/) with the latest `slip.js` as well as some changes I've made to `example.html`.  Just nice for those who find this library online.

**Comment by mahemoff** [comment]
Thanks @carter-thaxton, I'll need to re-integrate the library, will check it soon and let you know.
